version: "3"
services:
  catalog:
    build:
      context: ../../
      dockerfile: productcatalogue/Dockerfile
    image: ayoubensalem/spring:catalog
    user: root
    volumes:
      - mvnrepo:/home/test/.m2
      - ../../productcatalogue/target:/app/target
    command: mvn surefire-report:report
    networks:
      - labnet

  front:
    build:
      context: ../../
      dockerfile: shopfront/Dockerfile
    image: ayoubensalem/spring:front
    user: root
    volumes:
      - mvnrepo:/home/test/.m2
      - ../../shopfront/target:/app/target
    command: mvn surefire-report:report
    networks:
      - labnet

  stock:
    build:
      context: ../../
      dockerfile: stockmanager/Dockerfile
    image: ayoubensalem/spring:stock
    user: root
    volumes:
      - mvnrepo:/home/test/.m2
      - ../../stockmanager/target:/app/target
    command: mvn surefire-report:report
    networks:
      - labnet

volumes:
  mvnrepo:
  mysqldata:
networks:
  labnet:
