version: "3"

services:
  catalog:
    image: ayoubensalem/spring:catalog
    user: test
    volumes:
      - mvnrepo:/home/test/.m2
    command: mvn sonar:sonar
    networks:
      - labnet

  front:
    image: ayoubensalem/spring:front
    user: test
    volumes:
      - mvnrepo:/home/test/.m2
    command: mvn sonar:sonar
    networks:
      - labnet

  stock:
    image: ayoubensalem/spring:stock
    user: test
    volumes:
      - mvnrepo:/home/test/.m2
    command: mvn sonar:sonar
    networks:
      - labnet

volumes:
  mvnrepo:
networks:
  labnet:
