version: "3"

services:
  catalog:
    image: ayoubensalem/spring:catalog
    volumes:
      - mvnrepo:/home/test/.m2
    command: mvn sonar:sonar
    networks:
      - cvgnet1

  front:
    image: ayoubensalem/spring:front
    volumes:
      - mvnrepo:/home/test/.m2
    command: mvn sonar:sonar
    networks:
      - cvgnet2

  stock:
    image: ayoubensalem/spring:stock
    volumes:
      - mvnrepo:/home/test/.m2
    command: mvn sonar:sonar
    networks:
      - cvgnet3

volumes:
  mvnrepo:
networks:
  cvgnet1:
  cvgnet2:
  cvgnet3:
