version: "3.2"
services:
  catalog:
    build:
      context: ../../
      dockerfile: productcatalogue/Dockerfile
    image: ayoubensalem/spring:catalog
    user: test
    volumes:
      - type: volume
        source: /home/test/.m2
        target: /data
      - type: volume
        source: ../../productcatalogue/target
        target: /app/target
        mode: 0777
    networks:
      - labnet
  front:
    build:
      context: ../../
      dockerfile: shopfront/Dockerfile
    image: ayoubensalem/spring:front
    user: test
    volumes:
      - type: volume
        source: /home/test/.m2
        target: /data
      - type: volume
        source: ../../shopfront/target
        target: /app/target
        mode: 0777        
    networks:
      - labnet

  stock:
    build:
      context: ../../
      dockerfile: stockmanager/Dockerfile
    image: ayoubensalem/spring:stock
    user: test
    volumes:
      - type: volume
        source: /home/test/.m2
        target: /data
      - type: volume
        source: ../../stockmanager/target
        target: /app/target
        mode: 0777        
    networks:
      - labnet
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    image: ayoubensalem/agent
    depends_on:
      - db
    environment:
      PROBE_HOST: "db"
      PROBE_PORT: "3306"
    command: ["probe.yml"]
    networks:
      - labnet
#      docker run -e

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: ayoubensalem/springmysql:latest
    ports:
      - "33633:3306"
    volumes:
#      - ./dumps:/opt/dumps
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "19641995"
      MYSQL_DATABASE: "springdocker"
      MYSQL_USER: "ayoubensalem"
      MYSQL_PASSWORD: "19641995"
    networks:
      - labnet


volumes:
  mvnrepo:
  mysqldata:
networks:
  labnet:
