---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  labels:
    app: productcatalogue
spec:
  type: NodePort
  selector:
    app: productcatalogue
  ports:
  - protocol: TCP
    port: 8020
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalogue
  template:
    metadata:
      labels:
        app: productcatalogue
    spec:
      containers:
      - name: productcatalogue
        image: ayoubensalem/springcatalog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8020
        readinessProbe:
          exec:
            command: ["mysql", "-h", "db","-P", "3306", "-u", "ayoubensalem", "-p19641995","-e", "SELECT 1"]
          initialDelaySeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
      restartPolicy: Always
