FROM openjdk:8-jre

MAINTAINER ayoubensalem
ENV DB_HOST=db
ENV DB_PORT=3306
RUN mkdir /app
WORKDIR /app

RUN apt-get update \
&& apt-get install -y mysql-client
ADD shopfront/target/shopfront*.jar /app/app.jar
COPY shopfront/wait-for-it.sh ./wait-for-it.sh
RUN chmod +x /app/wait-for-it.sh
EXPOSE 8010
#ENTRYPOINT ["./wait-for-it.sh", "${DB_HOST}:${DB_PORT}"]
CMD ["java","-Djava.security.egd=file:/dev/./urandom","-jar","app.jar"]
# --PropertyName=NewValue