FROM openjdk:8-jre

MAINTAINER ayoubensalem



RUN apt-get update \
&& apt-get install -y mysql-client
RUN mkdir /app
WORKDIR /app
ENV DB_HOST=db
ENV DB_PORT=3306
ADD stockmanager/target/stockmanager*.jar app.jar
#COPY stockmanager/wait-for-it.sh ./wait-for-it.sh
#RUN chmod +x /app/wait-for-it.sh

EXPOSE 8030

#ENTRYPOINT ["./wait-for-it.sh", "${DB_HOST}:${DB_PORT}"]
CMD ["java","-Djava.security.egd=file:/dev/./urandom","-jar","app.jar"]
