--- # Playbook for setting up swarm cluster

  - name: Restart docker
    service:
      name: docker
      state: restarted

  - name: Init Swarm Master
    hosts: local
    gather_facts: False
    remote_user: jenkins
    tasks:
      - name: Leave Swarm Cluster
        command: docker swarm leave --force
        register: result
        failed_when: result.rc == 100

  - name: Restart docker
    service:
      name: docker
      state: restarted

  - name: Join Swarm Cluster
    hosts: slaves
    remote_user: ansible
    gather_facts: False
    tasks:
      - name: Leave Swarm Cluster
        command: docker swarm leave --force
        register: result
        failed_when: result.rc == 100
